### ISSUE TITLE
Copy as YAML option in context menu

### ISSUE THREAD

**Issue by hrvoj3e** [HeidiSQL/HeidiSQL#1846]
**Is your feature request related to a problem? Please describe.**
This would be nice.

**Describe the solution you'd like**
![image](https://github.com/HeidiSQL/HeidiSQL/assets/4988133/8dbf46d5-adca-46c2-900b-2e51fee7c0ab)

**Describe alternatives you've considered**
Online converter from JSON to YAML.

**Additional context**
YAML is nice, more readable and more compact.

**Comment by ansgarbecker** [comment]
I was just thinking YAML is only for configuration files, but reading its [Wikipedia page](https://en.wikipedia.org/wiki/YAML), I realize it was invented as a more generic format. I'm a bit confused by the shown examples, especially the more complex ones. So, could you please suggest a good and simple enough way which I can then adopt in HeidiSQL?

**Comment by hrvoj3e** [comment]
I would recommend using uxisting JSON format and convert it to YAML format with any available converter that you can integrate.
DB rows are too simple and we should not expect any problems.
If it works with JSON it will work with YAML 100%.


Here is HeidiSQL "Copy as" for one row from table `mysql.proc`
```json
{
	"table": "proc",
	"rows":
	[
		{
			"db": "mysql",
			"name": "AddGeometryColumn",
			"type": "PROCEDURE",
			"specific_name": "AddGeometryColumn",
			"language": "SQL",
			"sql_data_access": "CONTAINS_SQL",
			"is_deterministic": "NO",
			"security_type": "INVOKER",
			"param_list": "catalog varchar(64), t_schema varchar(64),\n   t_name varchar(64), geometry_column varchar(64), t_srid int",
			"returns": "",
			"body": "begin\n  set @qwe= concat('ALTER TABLE ', t_schema, '.', t_name, ' ADD ', geometry_column,' GEOMETRY REF_SYSTEM_ID=', t_srid); PREPARE ls from @qwe; execute ls; deallocate prepare ls; end",
			"definer": "mariadb.sys@localhost",
			"created": "2022-05-08 21:24:05",
			"modified": "2020-02-03 07:02:57",
			"sql_mode": "",
			"comment": "",
			"character_set_client": "utf8",
			"collation_connection": "utf8_general_ci",
			"db_collation": "utf8mb4_croatian_ci",
			"body_utf8": "begin\n  set @qwe= concat('ALTER TABLE ', t_schema, '.', t_name, ' ADD ', geometry_column,' GEOMETRY REF_SYSTEM_ID=', t_srid); PREPARE ls from @qwe; execute ls; deallocate prepare ls; end",
			"aggregate": "NONE"
		}
	]
}
```

YAML would look like (used [online converter](https://www.json2yaml.com/))
```yaml
---
table: proc
rows:
- db: mysql
  name: AddGeometryColumn
  type: PROCEDURE
  specific_name: AddGeometryColumn
  language: SQL
  sql_data_access: CONTAINS_SQL
  is_deterministic: 'NO'
  security_type: INVOKER
  param_list: |-
    catalog varchar(64), t_schema varchar(64),
       t_name varchar(64), geometry_column varchar(64), t_srid int
  returns: ''
  body: |-
    begin
      set @qwe= concat('ALTER TABLE ', t_schema, '.', t_name, ' ADD ', geometry_column,' GEOMETRY REF_SYSTEM_ID=', t_srid); PREPARE ls from @qwe; execute ls; deallocate prepare ls; end
  definer: mariadb.sys@localhost
  created: '2022-05-08 21:24:05'
  modified: '2020-02-03 07:02:57'
  sql_mode: ''
  comment: ''
  character_set_client: utf8
  collation_connection: utf8_general_ci
  db_collation: utf8mb4_croatian_ci
  body_utf8: |-
    begin
      set @qwe= concat('ALTER TABLE ', t_schema, '.', t_name, ' ADD ', geometry_column,' GEOMETRY REF_SYSTEM_ID=', t_srid); PREPARE ls from @qwe; execute ls; deallocate prepare ls; end
  aggregate: NONE

```
