### ISSUE TITLE
Need to temporarily switch to libmariadb.dll library to connect to Docker MySQL image

### ISSUE THREAD

**Issue by TechFanDan** [HeidiSQL/HeidiSQL#1865]
**Preconditions**

* HeidiSQL version: 12.0.0.6677
* Database type and version: MySQL 8.0
* OS: Windows 10 Home
* Docker 4.24.2

I kept getting the error: **Error: Access denied for user 'root'@'172.28.0.1' (using passowrd: YES)** when attempting to connect to the MySQL server even though everything was configured properly. It turns out, the fix is to switch to the libmariadb.dll library to initially establish the connection.

In a folder, create the following **docker-compose.yml** file:

```
version: "3.2"
services:
  mysql:
    container_name: mysql
    build: './mysql/'
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ROOT_HOST: "%"
      TZ: "-03:00"
    networks:
      - frontend
      - backend
    ports:
      - "3306:3306"
    volumes:
      - "$MYSQL_DATA:/var/lib/mysql"
networks:
  frontend:
  backend:
```
At the root, in the file **.env**, add the following code (and change the path accordingly):

```
MYSQL_ROOT_PASSWORD="root"
MYSQL_DATA=C:/Users/me/Downloads/docker_files/mysql/data
```

In **mariadb/Dockerfile**, add the following code:

```
FROM mysql:8.0
COPY conf/my.cnf /etc/my.cnf
```

In **mariadb/conf/my.cnf**, add the following code:
```

[mysqld]
skip-host-cache
skip-name-resolve
datadir=/var/lib/mysql
socket=/var/run/mysqld/mysqld.sock
secure-file-priv=/var/lib/mysql-files
user=mysql
bind-address=0.0.0.0
default-time-zone='-03:00'
general_log = 1
general_log_file = /var/log/mysql/mysql.log

#setting to 1 per recommendations, need to do this in Azure too.
lower_case_table_names=1

pid-file=/var/run/mysqld/mysqld.pid
[client]
socket=/var/run/mysqld/mysqld.sock

!includedir /etc/mysql/conf.d/
```

1. Run the docker-composer.yml file in order to bring up the container (ie. compose up). 
2. Configure a new session in HeidiSQL with the following parameters: Hostname: 127.0.0.1, User: "root", Password: "root" and Library libmysql.dll.
3. Click Open, which should bring up the popup message stating Access Denied.
4. Switch the library to libmariadb.dll which will establish the connection without any errors.

**Screenshots or Crash reports**
