### ISSUE TITLE
Better issue template

### ISSUE THREAD

**Issue by timint** [HeidiSQL/HeidiSQL#1996]
Hi, I want to recommend using githubs improved templates for issue tickets.
This will prohibit users (like myself) from removing the issue template and gives a better overview. 😄

`.github\ISSUE_TEMPLATE\bug_report.yml`

```
name: Bug Report
description: Create a bug report
labels: ["bug"]
body:
  - type: textarea
    attributes:
      label: Description
      description: "A clear and concise description of what the bug is. What did you expect? And what happened instead?"
      value: |
        ### What where you trying to do?


        ### What actually happened?


        ### What did you expect to happen?


    validations:
      required: true
  - type: input
    id: heidisql_version
    attributes:
      label: HeidiSQL Version
      description: "What is the version of HeidiSQL that produced this problem?"
      placeholder: "Example: 11.1.0.6210"
    validations:
      required: true
  - type: input
    id: database_software
    attributes:
      label: Database Server Version
      description: "What is the database software and version were you running when the problem occured?"
      placeholder: "Example: MariaDB 10.3.27"
    validations:
      required: true
  - type: textarea
    id: error_log
    attributes:
      label: Error/Backtrace
      description: If an error message was produced.
      render: shell
  - type: textarea
    attributes:
      label: Instructions for reproducing the problem
      description: "A clear and concise description of what the bug is. What did you expect? And what happened instead?"
      placeholder: ""
      value: |
1. Go to '...'
2. Click on '....'
3. See error message: xyz
    validations:
      required: false

```

Example of use:
![image](https://github.com/user-attachments/assets/ba6059f2-bc05-41e0-a87d-8268ac753fb4)
